targets:
  ngcomponents:
    sources:
      exclude: ["lib/builder.dart"]
    builders:
      sass_builder|sass_builder:
        enabled: False
      ngcomponents|scss_builder:
        enabled: True
  scss_builder:
    sources: ["lib/builder.dart"]
    dependencies:
      - build
      - sass_builder


builders:
  scss_builder:
    target: "scss_builder"
    import: "package:ngcomponents/builder.dart"
    builder_factories: ["scssBuilder"]
    build_to: cache
    build_extensions:
      .scss: [".scss.css"]
      .sass: [".scss.css"]
    applies_builders:
      - sass_builder|sass_source_cleanup
