# See https://github.com/google/mono_repo.dart for details
sdk:
  - 2.14.2
  - dev

stages:
  - build:
    - group:
      - command: dart pub run build_runner build web
      - command: dart pub run build_runner build web --release

cache:
  directories:
    - .dart_to